// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrXHBxPUp7Oa0JDzBE0-d5NmE_NZDRr1Y',
    appId: '1:440165350871:android:f83c79fade1acaae071f92',
    messagingSenderId: '440165350871',
    projectId: 'test-smart-control',
    databaseURL: 'https://test-smart-control-default-rtdb.firebaseio.com',
    storageBucket: 'test-smart-control.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9d6kwSIBg05GAV_1kikcFIS2VWQ1TqPc',
    appId: '1:440165350871:ios:518cedf9327606a7071f92',
    messagingSenderId: '440165350871',
    projectId: 'test-smart-control',
    databaseURL: 'https://test-smart-control-default-rtdb.firebaseio.com',
    storageBucket: 'test-smart-control.appspot.com',
    iosClientId: '440165350871-ol1j9coigab7f9vtio8f0b9kv7esgmv6.apps.googleusercontent.com',
    iosBundleId: 'com.example.tBtl',
  );
}
